#! /bin/sh
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d "Code" "Term" "TeX" "PDF" "Net" "Other"
# bspc monitor DP1 -d I II III IV V VI VII VIII IX X
bspc monitor DP1 -d I II III IV V 
bspc monitor HDMI1 -d I II III IV V 
# bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^4' 
bspc rule -a Zathura state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc config pointer_modifier mod2
# bspc config focus_follows_pointer true

# feh --bg-center ~/Pictures/My_Wallpapers/wallhaven-zmjd7o_1920x1080.png
# feh --bg-center ~/Pictures/My_Wallpapers/wallhaven-zmjd7o_1366x768.png
# feh --bg-center ~/Pictures/My_Wallpapers/Arch-2.png
# feh --bg-center ~/Pictures/My_Wallpapers/Wallhaven/wallhaven-7379v9_1366x768.png
# feh --bg-center ~/Pictures/My_Wallpapers/Arch-2.png
feh --bg-center ~/Pictures/My_Wallpapers/99-0.png
# wal -R
bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#00ff00'
# picom --active-opacity 0.95 --inactive-opacity 0.9 --frame-opacity 0.95 -c -b

killall picom; picom -c -b
killall ibus-daemon; ibus-daemon -drx
killall sxhkd; sxhkd &
killall polybar; polybar example &

setxkbmap us &
bspc rule -a dropdown sticky=on state=floating hidden=on locked=on
